# Tensor Basics
This notebook goes through the most basic and essential tensor operations to build TensorFlow 2.0
 understanding and intuition.

## Index
[Initialization of Tensors](#Initialization-of-Tensor)

[Mathematical Operations](#Mathematical-Operations)

[Indexing](#Indexing)

[Reshaping](#Reshaping)

In [1]:
# Import os
import os
# Lower verbose setting
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [2]:
# Import tensorflow
import tensorflow as tf
# Can be added to share memory
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

## Initialization of Tensors

In [3]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)


tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [4]:
# Matrix
x = tf.constant([[1, 2, 3], [4, 5, 6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
# All-ones matrix
x = tf.ones((3, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [6]:
# Zero matrix
x = tf.zeros((2, 4))
print(x)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32)


In [7]:
# Identity matrix
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [8]:
# Normal distribution
x = tf.random.normal((3, 3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 1.5325241  -0.30856162 -0.9785258 ]
 [ 1.8906679   1.8502159   0.496325  ]
 [ 0.5174802  -0.13090467 -0.3742027 ]], shape=(3, 3), dtype=float32)


In [9]:
# Uniform distribution
x = tf.random.uniform((1 , 3), minval=0, maxval=1)
print(x)

tf.Tensor([[0.10977983 0.39666688 0.71118164]], shape=(1, 3), dtype=float32)


In [10]:
# Range
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [11]:
# Stepped range
x = tf.range(start=1, limit=10, delta=2)
print(x)


tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [12]:
# Cast converts between different dtypes
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


## Mathematical Operations

In [13]:
# Element wise multiplication
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

# Add
z = tf.add(x, y)    # Same as z = x + y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [14]:
# Subtract
z = tf.subtract(x, y )  # Same as z = x - y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [15]:
# Divide
z = tf.divide(x, y)     # Same as z = x / y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [16]:
# Multiply
z = tf.multiply(x, y)   # Same as z = x * y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [17]:
# Dot product
z = tf.tensordot(x, y, axes=1)
print(z)


tf.Tensor(46, shape=(), dtype=int32)


In [18]:
# Exponential
z = x ** 5
print(z)


tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [21]:
# Matrix multiplication
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))
z = tf.matmul(x, y)     # Same as z = x @ y
print(z)


tf.Tensor(
[[-0.93531394  0.37667996  1.0641676   1.1817343 ]
 [ 0.7981661  -1.5587838   1.513402   -0.5166127 ]], shape=(2, 4), dtype=float32)


## Indexing


In [42]:
# Vector
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print([x[:]])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

[<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 1, 2, 3])>]
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [43]:
# Vector indexing
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [35]:
# Martix
x = tf.constant([[1, 3],
                 [3, 4],
                 [5, 6]])
print(x[0, :])
print(x[:2, :])

tf.Tensor([1 3], shape=(2,), dtype=int32)
tf.Tensor(
[[1 3]
 [3 4]], shape=(2, 2), dtype=int32)


## Reshaping

In [44]:
# Range
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [45]:
# 8,1 to 3,3
x = tf.reshape(x, (3, 3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [46]:
# Transpose
x = tf.transpose(x, perm=[1, 0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
